name: canary

on:
  pull_request:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.bot }} ${{ matrix.dart-version }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        bot:
          - analyzer
          - dartdoc
          - devtools
          - stagehand
          - webdev
        dart-version:
          - dev/release/latest
          - beta/release/latest
          - stable/release/2.10.1
          - stable/release/2.9.3
          - stable/release/2.8.4

    steps:
      - uses: actions/checkout@v2

      - name: Install Dart
        env:
          DART_VERSION: ${{ matrix.dart-version }}
        run: |
          ./.github/install-dart.sh
          echo "`pwd`/dart-sdk/bin" >> $GITHUB_PATH
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Test ${{ matrix.bot }}
        working-directory: ${{ matrix.bot }}
        run: ./test.sh
